### ISSUE TITLE
cut the left side of the border

### ISSUE THREAD

**Issue by Ehsan-Home** [kovart/dashed-border-generator#2]
Hi. Thanks for your amazing library 👍 
Super useful.

I'm going to use it for bordering. 
Do you have any idea how I can cut the left side of the border?
I mean, having a border only on top, right & bottom. 

Thanks in advance 💯

**Comment by kovart** [comment]
Hi, thank you for your words, it's very pleased for me.
Unfortunately SVG doesn't support partial strokes and I haven't time to research now 😔 
But you could try to use your own svg with lines instead of rect shape: https://vanseodesign.com/web-design/svg-fill-stroke/

**Comment by Ehsan-Home** [comment]
Hi. Thanks for your feedback,

I will take care of it.

Have a good day! 😃
